# Generated by Django 4.1.2 on 2022-10-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180403_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='efforts',
        ),
    ]
