# Generated by Django 4.1.2 on 2022-10-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_remove_company_city_alter_userprofile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='found_date',
        ),
    ]
